# Generated by Django 3.0.1 on 2022-10-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_auto_20221013_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
