# Generated by Django 3.0.1 on 2022-10-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20221014_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'blog_category', 'verbose_name_plural': 'blog_categories'},
        ),
    ]
