# Generated by Django 3.2 on 2022-11-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogcategory_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='category_name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
