# Generated by Django 3.2 on 2022-11-19 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogcategory_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='category_name',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z_]*$', 'Only uppercase letters and underscores allowed.')]),
        ),
    ]
