# Generated by Django 3.0.1 on 2022-09-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220914_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='score',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
