# Generated by Django 3.0.1 on 2022-10-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20221013_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('score',)},
        ),
        migrations.AddField(
            model_name='product',
            name='info',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
