# Generated by Django 3.0.1 on 2022-10-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20221013_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cons_1',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cons_2',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cons_3',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cons_4',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pros_1',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pros_2',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pros_3',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pros_4',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
