# Generated by Django 3.0.1 on 2022-10-13 19:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20221013_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='info',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
