# Generated by Django 3.0.1 on 2022-10-13 19:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20221013_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
