# Generated by Django 3.2 on 2022-10-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_product_thumbnail2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail2',
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='reviews'),
        ),
    ]
