# Generated by Django 3.2 on 2022-10-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20221014_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='more_info',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
