# Generated by Django 3.2 on 2022-10-14 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_product_more_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='more_info',
        ),
        migrations.RemoveField(
            model_name='product',
            name='more_info_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='more_info_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='more_info_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='more_info_6',
        ),
    ]
